name: upcom
version: 0.5.3
authors:
- Mike Lewis <mike@updroid.com>
- Don Huynh <don@updroid.com>
description: A browser-based IDE and omni-tool for robotics software development.
homepage: https://www.updroid.com/upcom
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  args: any
  http_server: '>=0.9.3 <0.10.0'
  logging: any
  logging_handlers: any
  bootjack: any
  browser: any
  collection: any
  dquery: any
  path: any
  quiver: any
  script_inliner: any
  upcom-api:
    path: ../upcom-api/
transformers:
- script_inliner
