name: updroidclient
description: A sample application
dependencies:
  ace: any
  bootjack: any
  browser: any
  collection: any
  dnd: any
  dquery: any
  path: any
  quiver: any
  script_inliner: any
  terminal:
    path: /home/crunchex/work/terminal
transformers:
- script_inliner
